global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'nwiizo-monitor'
rule_files: # アラートのルールに関する設定ファイル
  - /etc/prometheus/alert.rules
alerting: # アラートに関する設定
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - pushgateway:9091
